---
framework: mocha
licenseTier: small
postMerge: 
  pattern: 
    - "./test/**/*.spec.ts"
  strategy: 
    threshold: <5|100s|30m|6h>
    type: <commit|time>
preMerge:
  pattern:
    - "./test/**/*.spec.ts"
preRun:
     command:
        - npm ci
version: 1.2
